# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

# Define flags for per-crate coverage
flags:
  mcp-core:
    paths:
      - crates/mcp-core/
    carryforward: true
  mcp-introspector:
    paths:
      - crates/mcp-introspector/
    carryforward: true
  mcp-codegen:
    paths:
      - crates/mcp-codegen/
    carryforward: true
  mcp-files:
    paths:
      - crates/mcp-files/
    carryforward: true
  mcp-skill:
    paths:
      - crates/mcp-skill/
    carryforward: true
  mcp-server:
    paths:
      - crates/mcp-server/
    carryforward: true
  mcp-cli:
    paths:
      - crates/mcp-cli/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
