//! Integration tests for mcp-server.
//!
//! These tests verify the public API and state management of the mcp-server crate.
//! Note: MCP tool methods generated by #[tool] macro are private and tested via
//! unit tests in service.rs, so we focus on testing public types and state manager.

use chrono::Duration;
use mcp_execution_core::{ServerConfig, ServerId, ToolName};
use mcp_execution_introspector::{ServerCapabilities, ServerInfo, ToolInfo};
use mcp_execution_server::{
    CategorizedTool, GeneratorService, PendingGeneration, StateManager, SystemClock,
};
use rmcp::ServiceExt;
use rmcp::handler::server::ServerHandler;
use std::sync::Arc;
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};

// ============================================================================
// Service Initialization Tests
// ============================================================================

#[test]
fn test_service_info_has_correct_capabilities() {
    let service = GeneratorService::new();
    let info = service.get_info();

    // Verify protocol version
    assert_eq!(
        info.protocol_version,
        rmcp::model::ProtocolVersion::V_2025_06_18
    );

    // Verify tools are enabled
    assert!(info.capabilities.tools.is_some());
    let tools = info.capabilities.tools.as_ref().unwrap();
    assert!(!tools.list_changed.unwrap_or(false));

    // Verify instructions are provided
    assert!(info.instructions.is_some());
    let instructions = info.instructions.unwrap();
    assert!(instructions.contains("progressive loading"));
    assert!(instructions.contains("introspect_server"));
    assert!(instructions.contains("save_categorized_tools"));
}

/// Characterizes a currently accidental behavior (issue #381): `GeneratorService`
/// does not override [`ServerHandler::supported_protocol_versions`], so rmcp's
/// default advertises every protocol version the SDK knows — not just the
/// `2025-06-18` fallback `get_info()` pins for unrecognized-version negotiation.
/// This is a regression gate, not an endorsement: if a future rmcp release
/// changes `KNOWN_VERSIONS` or its default `supported_protocol_versions()`
/// implementation, this test fails loudly instead of the drift going unnoticed.
///
/// The expected list is written out explicitly rather than compared against
/// `ProtocolVersion::KNOWN_VERSIONS` itself — comparing a value against the very
/// constant it is derived from is a tautology that can't catch rmcp substituting
/// one version for another while keeping the same count.
#[test]
fn test_service_advertises_all_known_protocol_versions_by_default() {
    let service = GeneratorService::new();

    let expected = [
        rmcp::model::ProtocolVersion::V_2024_11_05,
        rmcp::model::ProtocolVersion::V_2025_03_26,
        rmcp::model::ProtocolVersion::V_2025_06_18,
        rmcp::model::ProtocolVersion::V_2025_11_25,
        rmcp::model::ProtocolVersion::V_2026_07_28,
    ];

    assert_eq!(
        service.supported_protocol_versions().as_ref(),
        expected.as_slice(),
        "supported_protocol_versions() is not overridden, so it must still equal \
         rmcp's full KNOWN_VERSIONS set; if this fails, rmcp's default changed"
    );
}

/// Characterizes the `server/discover` response `GeneratorService` currently
/// produces (issue #381), reproducing `ServerHandler::discover`'s default logic
/// (`DiscoverResult::from_server_info(supported_protocol_versions(), get_info())`,
/// see rmcp's `handler/server.rs`) directly against the service's public methods.
/// `from_server_info` moves `supported_versions` through verbatim, so this test's
/// value is in pinning that the *other* fields (`instructions`, `capabilities`,
/// `server_info`) are also carried over correctly; the real wire-level `discover()`
/// round-trip — which this reproduction cannot catch a future clamp inside
/// `discover()` itself from breaking — is covered separately by
/// `test_discover_rpc_round_trip_reports_all_known_versions` below.
#[test]
fn test_discover_result_from_server_info_reports_all_known_versions() {
    let service = GeneratorService::new();
    let info = service.get_info();
    let expected_capabilities = info.capabilities.clone();
    let expected_instructions = info.instructions.clone();

    let discover_result = rmcp::model::DiscoverResult::from_server_info(
        service.supported_protocol_versions().into_owned(),
        info,
    );

    assert_eq!(
        discover_result.supported_versions,
        rmcp::model::ProtocolVersion::KNOWN_VERSIONS.to_vec()
    );
    assert_eq!(discover_result.capabilities, expected_capabilities);
    assert_eq!(discover_result.instructions, expected_instructions);
    assert_eq!(
        discover_result.server_info(),
        Some(rmcp::model::Implementation::new(
            env!("CARGO_PKG_NAME"),
            env!("CARGO_PKG_VERSION")
        ))
    );
}

/// Exercises the real `server/discover` RPC handler end to end over an in-process
/// duplex transport — not a reproduction of its default logic (see the test
/// above) — so a future rmcp release that clamps `discover()`'s response to
/// `get_info().protocol_version`, rather than the full `supported_protocol_versions()`
/// set, would be caught here even if it left `ServerHandler`'s method-level
/// defaults untouched.
///
/// `server/discover` always requires the SEP-2575 inline-lifecycle `_meta` pair
/// (`io.modelcontextprotocol/protocolVersion` + `.../clientCapabilities`) on the
/// request itself, even on a session that already completed `initialize` — rmcp's
/// `handler/server.rs` unconditionally requires request metadata for
/// `ClientRequest::DiscoverRequest`, regardless of the session's negotiated
/// protocol version. Both keys live nested inside `params._meta` on the wire
/// (rmcp's `Request<M, P>` `Deserialize` impl extracts `_meta` from `params`,
/// not from the top-level JSON-RPC envelope).
#[tokio::test]
async fn test_discover_rpc_round_trip_reports_all_known_versions() {
    let (client, server) = tokio::io::duplex(64 * 1024);
    let (server_read, server_write) = tokio::io::split(server);
    let (client_read, mut client_write) = tokio::io::split(client);

    let service_task = tokio::spawn(async move {
        let service = GeneratorService::new()
            .serve((server_read, server_write))
            .await
            .expect("initialize handshake must succeed over the duplex stream");
        service.waiting().await
    });

    let mut client_reader = BufReader::new(client_read);

    client_write
        .write_all(
            br#"{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"test-client","version":"0.0.0"}}}
"#,
        )
        .await
        .expect("write initialize request");

    let mut init_response = String::new();
    tokio::time::timeout(
        std::time::Duration::from_secs(5),
        client_reader.read_line(&mut init_response),
    )
    .await
    .expect("initialize response must arrive within 5s")
    .expect("read initialize response");
    assert!(
        init_response.contains(r#""id":1"#),
        "expected an initialize response, got: {init_response}"
    );

    client_write
        .write_all(
            br#"{"jsonrpc":"2.0","id":2,"method":"server/discover","params":{"_meta":{"io.modelcontextprotocol/protocolVersion":"2025-06-18","io.modelcontextprotocol/clientCapabilities":{}}}}
"#,
        )
        .await
        .expect("write server/discover request");

    let mut discover_response = String::new();
    tokio::time::timeout(
        std::time::Duration::from_secs(5),
        client_reader.read_line(&mut discover_response),
    )
    .await
    .expect("discover response must arrive within 5s")
    .expect("read discover response");

    let response: serde_json::Value =
        serde_json::from_str(&discover_response).unwrap_or_else(|e| {
            panic!("discover response must be valid JSON: {e}, got: {discover_response}")
        });
    assert!(
        response.get("error").is_none(),
        "expected a successful discover response, got an error: {discover_response}"
    );
    let supported_versions: Vec<&str> = response["result"]["supportedVersions"]
        .as_array()
        .unwrap_or_else(|| {
            panic!("response must include a supportedVersions array, got: {discover_response}")
        })
        .iter()
        .map(|v| {
            v.as_str().unwrap_or_else(|| {
                panic!("supportedVersions entries must be strings, got: {discover_response}")
            })
        })
        .collect();

    let expected: Vec<&str> = rmcp::model::ProtocolVersion::KNOWN_VERSIONS
        .iter()
        .map(rmcp::model::ProtocolVersion::as_str)
        .collect();
    assert_eq!(supported_versions, expected);

    drop(client_write);
    drop(client_reader);
    let _ = tokio::time::timeout(std::time::Duration::from_secs(5), service_task).await;
}

#[test]
fn test_service_new_creates_fresh_instance() {
    let service1 = GeneratorService::new();
    let service2 = GeneratorService::new();

    // Each service should be a separate instance
    let info1 = service1.get_info();
    let info2 = service2.get_info();

    // Both should have the same capabilities
    assert_eq!(info1.protocol_version, info2.protocol_version);
    assert!(info1.capabilities.tools.is_some());
    assert!(info2.capabilities.tools.is_some());
}

// ============================================================================
// State Management Integration Tests
// ============================================================================

#[tokio::test]
async fn test_state_manager_workflow() {
    let state = StateManager::new();

    // Create test server info
    let server_id = ServerId::new("test-server").unwrap();
    let server_info = create_test_server_info(server_id.clone());

    let config = ServerConfig::builder()
        .command("echo".to_string())
        .build()
        .unwrap();

    // Store pending generation
    let pending = PendingGeneration::new(server_id, server_info, config, None, &SystemClock);
    let session_id = state.store(pending.clone()).await.unwrap();

    // Verify it's stored
    assert_eq!(state.pending_count().await, 1);

    // Retrieve it
    let retrieved = state.take(session_id).await;
    assert!(retrieved.is_some(), "Should retrieve stored session");
    assert_eq!(retrieved.unwrap().server_id, pending.server_id);

    // Verify it's consumed
    assert_eq!(state.pending_count().await, 0);

    // Second take should fail
    let second = state.take(session_id).await;
    assert!(second.is_none(), "Session should be consumed");
}

#[tokio::test]
async fn test_multiple_concurrent_sessions() {
    let state = StateManager::new();

    // Create multiple pending generations
    let mut sessions = Vec::new();
    for i in 0..5 {
        let server_id = ServerId::new(&format!("server-{i}")).unwrap();
        let server_info = ServerInfo {
            id: server_id.clone(),
            name: format!("Server {i}"),
            version: "1.0.0".to_string(),
            capabilities: ServerCapabilities {
                supports_tools: true,
                supports_resources: false,
                supports_prompts: false,
            },
            tools: vec![],
        };

        let config = ServerConfig::builder()
            .command("echo".to_string())
            .build()
            .unwrap();

        let pending = PendingGeneration::new(server_id, server_info, config, None, &SystemClock);
        let session_id = state.store(pending).await.unwrap();
        sessions.push(session_id);
    }

    // Verify all sessions are accessible
    assert_eq!(state.pending_count().await, 5);

    // Retrieve each session
    for session_id in sessions {
        let retrieved = state.take(session_id).await;
        assert!(retrieved.is_some(), "Session should be retrievable");
    }

    // All sessions should be consumed
    assert_eq!(state.pending_count().await, 0);
}

#[tokio::test]
async fn test_state_manager_handles_expiration() {
    let state = StateManager::new();

    let server_id = ServerId::new("test").unwrap();
    let server_info = create_test_server_info(server_id.clone());
    let config = ServerConfig::builder()
        .command("echo".to_string())
        .build()
        .unwrap();

    // Create and manually expire a session
    let mut pending = PendingGeneration::new(server_id, server_info, config, None, &SystemClock);
    pending.expires_at = chrono::Utc::now() - Duration::hours(1);

    let session_id = state.store(pending).await.unwrap();

    // Should not be retrievable (expired)
    let retrieved = state.take(session_id).await;
    assert!(
        retrieved.is_none(),
        "Expired session should not be retrievable"
    );

    // Pending count should be 0 (expired sessions are cleaned up)
    assert_eq!(state.pending_count().await, 0);
}

#[tokio::test]
async fn test_state_manager_lazy_cleanup() {
    let state = StateManager::new();

    // Create valid session
    let valid_pending = create_test_pending("valid-server");
    state.store(valid_pending).await.unwrap();

    // Create expired session
    let mut expired_pending = create_test_pending("expired-server");
    expired_pending.expires_at = chrono::Utc::now() - Duration::hours(1);
    state.store(expired_pending).await.unwrap();

    // Pending count should only include valid sessions
    assert_eq!(state.pending_count().await, 1);

    // Explicit cleanup
    let removed = state.cleanup_expired().await;
    assert_eq!(removed, 1, "Should remove 1 expired session");
}

#[tokio::test]
async fn test_state_manager_get_without_consuming() {
    let state = StateManager::new();

    let pending = create_test_pending("test");
    let session_id = state.store(pending).await.unwrap();

    // Get without consuming
    let first = state.get(session_id).await;
    assert!(first.is_some());

    // Should still be available
    let second = state.get(session_id).await;
    assert!(second.is_some());

    // Should still be available for take
    let taken = state.take(session_id).await;
    assert!(taken.is_some());

    // Now it should be gone
    let gone = state.get(session_id).await;
    assert!(gone.is_none());
}

// ============================================================================
// PendingGeneration Tests
// ============================================================================

#[test]
fn test_pending_generation_not_expired_initially() {
    let pending = create_test_pending("test");
    assert!(!pending.is_expired(&SystemClock));
}

#[test]
fn test_pending_generation_expires_correctly() {
    let mut pending = create_test_pending("test");
    pending.expires_at = chrono::Utc::now() - Duration::minutes(1);
    assert!(pending.is_expired(&SystemClock));
}

#[test]
fn test_pending_generation_has_correct_timeout() {
    let pending = create_test_pending("test");

    let duration = pending.expires_at - pending.created_at;
    let minutes = duration.num_minutes();

    assert_eq!(
        minutes,
        PendingGeneration::DEFAULT_TIMEOUT_MINUTES,
        "Should use default timeout"
    );
}

// ============================================================================
// CategorizedTool Tests
// ============================================================================

#[test]
fn test_categorized_tool_serialization_roundtrip() {
    let tool = CategorizedTool {
        name: "test_tool".to_string(),
        category: "testing".to_string(),
        keywords: "test,tool,demo".to_string(),
        short_description: "A test tool".to_string(),
    };

    let json = serde_json::to_string(&tool).unwrap();
    let deserialized: CategorizedTool = serde_json::from_str(&json).unwrap();

    assert_eq!(deserialized.name, tool.name);
    assert_eq!(deserialized.category, tool.category);
    assert_eq!(deserialized.keywords, tool.keywords);
    assert_eq!(deserialized.short_description, tool.short_description);
}

// ============================================================================
// Concurrent Access Tests
// ============================================================================

#[tokio::test]
async fn test_state_manager_concurrent_access() {
    let state = Arc::new(StateManager::new());
    let mut handles = vec![];

    // Spawn 10 concurrent store operations
    for i in 0..10 {
        let state_clone = Arc::clone(&state);
        handles.push(tokio::spawn(async move {
            let pending = create_test_pending(&format!("server-{i}"));
            state_clone.store(pending).await
        }));
    }

    // Wait for all operations to complete
    let mut session_ids = Vec::new();
    for handle in handles {
        let session_id = handle.await.unwrap().unwrap();
        session_ids.push(session_id);
    }

    // All sessions should be stored
    assert_eq!(state.pending_count().await, 10);

    // All session IDs should be unique
    let unique_count = session_ids
        .iter()
        .collect::<std::collections::HashSet<_>>()
        .len();
    assert_eq!(unique_count, 10, "All session IDs should be unique");
}

#[tokio::test]
async fn test_state_manager_concurrent_read_write() {
    let state = Arc::new(StateManager::new());

    // Store initial session
    let pending = create_test_pending("test");
    let session_id = state.store(pending).await.unwrap();

    let state_clone1 = Arc::clone(&state);
    let state_clone2 = Arc::clone(&state);

    // Concurrent reads should work
    let handle1 = tokio::spawn(async move { state_clone1.get(session_id).await });

    let handle2 = tokio::spawn(async move { state_clone2.get(session_id).await });

    let result1 = handle1.await.unwrap();
    let result2 = handle2.await.unwrap();

    assert!(result1.is_some());
    assert!(result2.is_some());
}

// ============================================================================
// Helper Functions
// ============================================================================

fn create_test_server_info(server_id: ServerId) -> ServerInfo {
    ServerInfo {
        id: server_id,
        name: "Test Server".to_string(),
        version: "1.0.0".to_string(),
        capabilities: ServerCapabilities {
            supports_tools: true,
            supports_resources: false,
            supports_prompts: false,
        },
        tools: vec![ToolInfo {
            name: ToolName::new("test_tool").unwrap(),
            description: "A test tool".to_string(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "message": {"type": "string"}
                },
                "required": ["message"]
            }),
            output_schema: None,
        }],
    }
}

fn create_test_pending(server_id_str: &str) -> PendingGeneration {
    let server_id = ServerId::new(server_id_str).unwrap();
    let server_info = create_test_server_info(server_id.clone());
    let config = ServerConfig::builder()
        .command("echo".to_string())
        .build()
        .unwrap();

    PendingGeneration::new(server_id, server_info, config, None, &SystemClock)
}
